/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-i18n-type-generator. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-i18n' {
  export interface DefineLocaleMessage extends I18nMessages {}
}

export interface I18nMessages {
  common: {
    yesOrNo: {
      yes: string;
      no: string;
    }
    userCenter: string;
    logout: string;
  }
}
