/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(public)/login/': RouteRecordInfo<'/(public)/login/', '/login', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)': RouteRecordInfo<'/(admin)/(base-layout)', '/', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/': RouteRecordInfo<'/(admin)/(base-layout)/', '/', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/system/user/': RouteRecordInfo<'/(admin)/(base-layout)/system/user/', '/system/user', Record<never, never>, Record<never, never>>,
    '/(admin)/(empty-layout)': RouteRecordInfo<'/(admin)/(empty-layout)', '/', Record<never, never>, Record<never, never>>,
    '/(admin)/(empty-layout)/[...path]': RouteRecordInfo<'/(admin)/(empty-layout)/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/(admin)/(empty-layout)/403/': RouteRecordInfo<'/(admin)/(empty-layout)/403/', '/403', Record<never, never>, Record<never, never>>,
    '/(admin)/(empty-layout)/500/': RouteRecordInfo<'/(admin)/(empty-layout)/500/', '/500', Record<never, never>, Record<never, never>>,
  }
}
