/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(admin)/(base-layout)': RouteRecordInfo<'/(admin)/(base-layout)', '/', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/': RouteRecordInfo<'/(admin)/(base-layout)/', '/', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/about/': RouteRecordInfo<'/(admin)/(base-layout)/about/', '/about', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/example/chart/': RouteRecordInfo<'/(admin)/(base-layout)/example/chart/', '/example/chart', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/example/copy/': RouteRecordInfo<'/(admin)/(base-layout)/example/copy/', '/example/copy', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/example/count-to/': RouteRecordInfo<'/(admin)/(base-layout)/example/count-to/', '/example/count-to', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/example/data-table/': RouteRecordInfo<'/(admin)/(base-layout)/example/data-table/', '/example/data-table', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/example/icon/': RouteRecordInfo<'/(admin)/(base-layout)/example/icon/', '/example/icon', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/example/page-transfer/': RouteRecordInfo<'/(admin)/(base-layout)/example/page-transfer/', '/example/page-transfer', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/example/page-transfer/transferred': RouteRecordInfo<'/(admin)/(base-layout)/example/page-transfer/transferred', '/example/page-transfer/transferred', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/example/rich-text/': RouteRecordInfo<'/(admin)/(base-layout)/example/rich-text/', '/example/rich-text', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/example/table-auto-height/': RouteRecordInfo<'/(admin)/(base-layout)/example/table-auto-height/', '/example/table-auto-height', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/multi-menu/first-child/': RouteRecordInfo<'/(admin)/(base-layout)/multi-menu/first-child/', '/multi-menu/first-child', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/multi-menu/second-child/': RouteRecordInfo<'/(admin)/(base-layout)/multi-menu/second-child/', '/multi-menu/second-child', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/multi-menu/third-child/': RouteRecordInfo<'/(admin)/(base-layout)/multi-menu/third-child/', '/multi-menu/third-child', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/system/api/': RouteRecordInfo<'/(admin)/(base-layout)/system/api/', '/system/api', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/system/api/[mode]/[id]': RouteRecordInfo<'/(admin)/(base-layout)/system/api/[mode]/[id]', '/system/api/:mode/:id', { mode: ParamValue<true>, id: ParamValue<true> }, { mode: ParamValue<false>, id: ParamValue<false> }>,
    '/(admin)/(base-layout)/system/menu/': RouteRecordInfo<'/(admin)/(base-layout)/system/menu/', '/system/menu', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/system/menu/[mode]/[id]': RouteRecordInfo<'/(admin)/(base-layout)/system/menu/[mode]/[id]', '/system/menu/:mode/:id', { mode: ParamValue<true>, id: ParamValue<true> }, { mode: ParamValue<false>, id: ParamValue<false> }>,
    '/(admin)/(base-layout)/system/role/': RouteRecordInfo<'/(admin)/(base-layout)/system/role/', '/system/role', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/system/role/[mode]/[id]': RouteRecordInfo<'/(admin)/(base-layout)/system/role/[mode]/[id]', '/system/role/:mode/:id', { mode: ParamValue<true>, id: ParamValue<true> }, { mode: ParamValue<false>, id: ParamValue<false> }>,
    '/(admin)/(base-layout)/system/user/': RouteRecordInfo<'/(admin)/(base-layout)/system/user/', '/system/user', Record<never, never>, Record<never, never>>,
    '/(admin)/(base-layout)/system/user/[mode]/[id]': RouteRecordInfo<'/(admin)/(base-layout)/system/user/[mode]/[id]', '/system/user/:mode/:id', { mode: ParamValue<true>, id: ParamValue<true> }, { mode: ParamValue<false>, id: ParamValue<false> }>,
    '/(admin)/(empty-layout)': RouteRecordInfo<'/(admin)/(empty-layout)', '/', Record<never, never>, Record<never, never>>,
    '/(admin)/(empty-layout)/[...path]': RouteRecordInfo<'/(admin)/(empty-layout)/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/(admin)/(empty-layout)/403/': RouteRecordInfo<'/(admin)/(empty-layout)/403/', '/403', Record<never, never>, Record<never, never>>,
    '/(admin)/(empty-layout)/500/': RouteRecordInfo<'/(admin)/(empty-layout)/500/', '/500', Record<never, never>, Record<never, never>>,
    '/(public)/login/': RouteRecordInfo<'/(public)/login/', '/login', Record<never, never>, Record<never, never>>,
  }
}
